import type { Session } from "@supabase/supabase-js";
import { requestPersonalizationRefresh } from "./personalizationRefresh";
const API_URL = import.meta.env.VITE_API_URL ?? import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";
const SESSION_KEY = "myntra-sync:analytics-session";
const SESSION_STARTED_AT = "myntra-sync:analytics-session-started-at";
const PRODUCT_VIEW_COOLDOWN_MS = 20_000;
const recentProductViews = new Map<string, number>();
export type AnalyticsEventType = "PRODUCT_VIEW" | "PRODUCT_DWELL" | "CATEGORY_VIEW" | "BRAND_VIEW" | "WISHLIST_ADD" | "WISHLIST_REMOVE" | "BAG_ADD" | "BAG_REMOVE" | "SEARCH" | "ORDER_PLACED" | "SESSION_START" | "SESSION_END";
export type AnalyticsEvent = { eventType: AnalyticsEventType; category?: string; brand?: string; productId?: string; color?: string; style?: string; occasion?: string; price?: number; durationSeconds?: number; sessionId?: string; metadata?: Record<string, unknown> };
export type AnalyticsSummary = { topCategories: { name: string; value: number }[]; favoriteBrands: { name: string; value: number }[]; peakShoppingHour: string; shoppingStyle: string; totalBrowsingTime: number };
export type ShoppingInsights = { summary: { browsing_time: number; products_viewed: number; categories_explored: number; wishlist_additions: number; bag_additions: number; brands_explored: number; event_count: number; compared_to_yesterday: number }; categories: { name: string; seconds: number }[]; timeline: { time: string; action: string }[]; personality: { title: string; description: string; reason?: string }; weekly: { day: number; label: string; value: number }[] };
export function analyticsSessionId(): string { let id = window.sessionStorage.getItem(SESSION_KEY); if (!id) { id = crypto.randomUUID(); window.sessionStorage.setItem(SESSION_KEY, id); window.sessionStorage.setItem(SESSION_STARTED_AT, String(Date.now())); } return id; }
export function analyticsSessionDuration(): number { const start = Number(window.sessionStorage.getItem(SESSION_STARTED_AT) || Date.now()); return Math.max(0, Math.round((Date.now() - start) / 1000)); }
function eventId(): string { return crypto.randomUUID(); }
/** Records only deliberate interactions. Product views are deduplicated per product/session for 20 seconds. */
export function trackEvent(session: Session | null, event: AnalyticsEvent): void { if (!session?.access_token) return; if (event.eventType === "PRODUCT_VIEW" && event.productId) { const key = `${analyticsSessionId()}:${event.productId}`; const previous = recentProductViews.get(key) ?? 0; if (Date.now() - previous < PRODUCT_VIEW_COOLDOWN_MS) return; recentProductViews.set(key, Date.now()); } const payload = { ...event, eventId: eventId(), sessionId: event.sessionId ?? analyticsSessionId(), metadata: { ...event.metadata, clientCreatedAt: new Date().toISOString() } }; if (event.eventType === "PRODUCT_VIEW") console.debug("PRODUCT_VIEW fired", { component: event.metadata?.component ?? "Unknown", product_id: event.productId, route: window.location.pathname, timestamp: new Date().toISOString() }); void fetch(`${API_URL}/behavior/event`, { method: "POST", keepalive: true, headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(payload) }).then((response) => { if (response.ok && event.eventType !== "SESSION_END") requestPersonalizationRefresh(); }).catch(() => undefined); }
export async function fetchAnalyticsSummary(session: Session): Promise<AnalyticsSummary> { const response = await fetch(`${API_URL}/analytics/summary`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) throw new Error("Analytics are unavailable."); return response.json() as Promise<AnalyticsSummary>; }
export async function fetchShoppingInsights(session: Session): Promise<ShoppingInsights> { const response = await fetch(`${API_URL}/analytics/shopping-insights`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) throw new Error("Shopping insights are unavailable."); return response.json() as Promise<ShoppingInsights>; }
