import { useEffect, useRef, useState, type ReactNode } from "react";
import { motion, useInView } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import type { Session } from "@supabase/supabase-js";
import { fetchShoppingInsights } from "../services/analyticsService";

const formatDuration = (seconds: number) => seconds >= 3600 ? `${Math.floor(seconds / 3600)} hr ${Math.round((seconds % 3600) / 60)} min` : `${Math.max(0, Math.round(seconds / 60))} min`;
function Count({ value }: { value: number }) { const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true }); const [count, setCount] = useState(0); useEffect(() => { if (!visible) return; let frame = 0; const start = performance.now(); const animate = (now: number) => { const progress = Math.min(1, (now - start) / 750); setCount(Math.round(value * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) frame = requestAnimationFrame(animate); }; frame = requestAnimationFrame(animate); return () => cancelAnimationFrame(frame); }, [value, visible]); return <span ref={ref}>{count}</span>; }
function Loading() { return <div className="space-y-5 animate-pulse"><div className="h-52 rounded-3xl bg-[#FFF0F4]" /><div className="grid gap-4 md:grid-cols-2"><div className="h-64 rounded-3xl bg-[#F5F5F6]" /><div className="h-64 rounded-3xl bg-[#F5F5F6]" /></div></div>; }
export default function ShoppingInsights({ session }: { session: Session | null }) { const query = useQuery({ queryKey: ["shopping-insights", session?.user.id], queryFn: () => fetchShoppingInsights(session!), enabled: Boolean(session), staleTime: 60_000 }); if (query.isLoading) return <Loading />; if (query.isError) return <div className="rounded-3xl border border-red-100 bg-red-50 p-6 text-sm text-red-700">Shopping insights are unavailable. <button className="font-bold underline" onClick={() => void query.refetch()}>Try again</button></div>; const data = query.data; if (!data || !data.summary.event_count) return <div className="rounded-3xl border border-dashed border-[#EAEAEC] bg-gradient-to-br from-[#FFF8FA] to-white px-6 py-16 text-center"><p className="text-3xl">✦</p><h2 className="mt-3 text-xl font-extrabold">Your shopping story is just beginning</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#777]">Browse a few products and Myntra-Sync will turn your real-time activity into more personal recommendations.</p></div>; const { summary, categories, timeline, personality, weekly } = data;

const validCategories = categories.filter(
  (item) => item.name?.trim()
); const maxCategory = Math.max(
  ...validCategories.map((item) => item.seconds),
  1
); const maxWeek = Math.max(...weekly.map((item) => item.value), 1); const metrics = [["Products Viewed", summary.products_viewed], ["Wishlist Adds", summary.wishlist_additions], ["Bag Adds", summary.bag_additions], ["Brands Explored", summary.brands_explored], ["Categories Explored", summary.categories_explored]]; const insight = categories[0] ? `You spend ${Math.max(1, Math.round(categories[0].seconds / Math.max(categories[1]?.seconds || 1, 1) * 10) / 10)}× longer exploring ${categories[0].name} than your next category. Recommendations are now prioritizing it.` : "Your live browsing behaviour is already helping Myntra-Sync refine what appears next."; return <div className="space-y-6">
  <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#2B2130] via-[#6B2144] to-[#FF3F6C] p-6 text-white shadow-[0_16px_40px_rgba(255,63,108,.2)] md:p-7"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-white/70">Live behaviour signal</p><div className="mt-2 flex flex-col justify-between gap-5 md:flex-row"><div><h2 className="font-editorial text-3xl">Shopping Behaviour</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">Understand how your browsing patterns shape personalized recommendations.</p><p className="mt-6 text-4xl font-extrabold tracking-tight">{formatDuration(summary.browsing_time)}</p><p className="mt-1 text-xs font-bold text-[#FFD6E1]">{summary.compared_to_yesterday >= 0 ? "+" : ""}{summary.compared_to_yesterday}% compared to yesterday</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 md:w-[430px]"><Metric label="Products" value={summary.products_viewed} /><Metric label="Categories" value={summary.categories_explored} /><Metric label="Wishlisted" value={summary.wishlist_additions} /><Metric label="In bag" value={summary.bag_additions} /></div></div></motion.section>
  <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-[#EAEAEC] bg-white p-5"><Kicker>Category Attention</Kicker><h2 className="mt-1 text-lg font-extrabold">Where your attention stayed</h2><div className="mt-5 space-y-4">{validCategories.map((item, index) => <div key={item.name}><div className="mb-2 flex justify-between text-xs font-bold"><span>{item.name}</span><span className="text-[#777]">{formatDuration(item.seconds)}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#F5F5F6]"><motion.div initial={{ width: 0 }} animate={{ width: `${Math.max(8, item.seconds / maxCategory * 100)}%` }} transition={{ delay: index * .08, duration: .65 }} className="h-full rounded-full bg-gradient-to-r from-[#FF3F6C] to-[#FF9AB3]" /></div></div>)}</div></section><section className="rounded-3xl border border-[#EAEAEC] bg-[#FFFCFD] p-5"><Kicker>Shopping Timeline</Kicker><h2 className="mt-1 text-lg font-extrabold">Your latest trail</h2><div className="mt-5 space-y-0">{timeline.map((item, index) => <div key={`${item.time}-${item.action}`} className="flex gap-3"><div className="flex flex-col items-center"><i className="mt-1.5 block h-2.5 w-2.5 rounded-full bg-[#FF3F6C]" />{index < timeline.length - 1 && <i className="h-9 w-px bg-[#FFD6E1]" />}</div><div className="pb-3"><p className="text-[10px] font-extrabold text-[#FF3F6C]">{item.time}</p><p className="mt-0.5 text-sm font-bold">{item.action}</p></div></div>)}</div></section></div>
  <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl bg-gradient-to-br from-[#FFF0F4] to-[#FFF9FB] p-6"><Kicker>AI Shopping Personality</Kicker><h2 className="mt-2 font-editorial text-3xl text-[#5D1634]">{personality.title}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#6A5360]">{personality.description}</p></div><div className="rounded-3xl border border-[#FFD5E0] bg-white p-6"><Kicker>AI Insight</Kicker><p className="mt-3 text-lg font-extrabold leading-7">{insight}</p><p className="mt-4 text-xs leading-5 text-[#777]">This live signal automatically influences the ordering of your next recommendations.</p></div></section>
  <section><Kicker>Engagement Metrics</Kicker><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-5">{metrics.map(([label, value]) => <motion.div whileHover={{ y: -4 }} key={String(label)} className="rounded-2xl border border-[#EAEAEC] bg-white p-4 shadow-sm"><p className="text-[10px] font-extrabold uppercase tracking-wide text-[#94969F]">{label}</p><p className="mt-2 text-2xl font-extrabold"><Count value={Number(value)} /></p></motion.div>)}</div></section>
  <section className="rounded-3xl border border-[#EAEAEC] bg-white p-5"><Kicker>Weekly Heatmap</Kicker><h2 className="mt-1 text-lg font-extrabold">Your browsing rhythm</h2><div className="mt-6 flex h-32 items-end gap-2 sm:gap-4">{weekly.map((item, index) => <div key={item.day} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-24 w-full items-end rounded-xl bg-[#FFF4F7] px-1"><motion.div initial={{ height: 0 }} animate={{ height: `${Math.max(item.value ? 12 : 0, item.value / maxWeek * 100)}%` }} transition={{ delay: index * .06, duration: .55 }} className="w-full rounded-lg bg-gradient-to-t from-[#FF3F6C] to-[#FF9AB3]" /></div><span className="text-[10px] font-extrabold text-[#777]">{item.label}</span></div>)}</div></section>
</div>; }
function Kicker({ children }: { children: ReactNode }) { return <p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#FF3F6C]">{children}</p>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/15 bg-white/10 p-3 backdrop-blur"><p className="text-[9px] font-extrabold uppercase tracking-wide text-white/65">{label}</p><p className="mt-1 text-lg font-extrabold">{value}</p></div>; }
